babycode/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path, include

from users import views as user_views


from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from game_logs import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("game_logs.urls")),
    path("register/", user_views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("profile/", user_views.profile, name="profile"),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("confirm/", views.confirm, name="confirm"),
    path("validate/", views.validate_email, name="validate_email"),
    path("donate/", include("donate.urls"), name="donate"),
    path("order/", include("order_drawings.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

donate/urls.py
from django.urls import path
from . import views


app_name = "donate"

urlpatterns = [
    path("", views.index, name="index"),
    path("charge/", views.charge, name="charge"),
    path("success/<str:args>/", views.successMsg, name="success"),
    path(
        "machinecode/<int:pk>/",
        views.MachineCodeDonateView.as_view(),
        name="machinecode",
    ),
    path("humancode/<int:pk>/", views.HumanCodeDonateView.as_view(), name="humancode"),
]

game_logs/urls.py
"""Defines URL patterns for game_logs"""

from django.urls import path
from . import views
from .views import GameDemoListView, GameDetailCreateView


app_name = "game_logs"

urlpatterns = [
    # Home page
    path("", GameDemoListView.as_view(), name="homepage"),
    path("about/", views.about, name="about"),
    path("game-detail/<int:pk>/", GameDetailCreateView.as_view(), name="game-detail"),
]

donate/models.py
from django.db import models

# Create your models here.

donate/forms.py
from django import forms


class ConfirmForm(forms.Form):
    confirm_status = forms.BooleanField(
        required=True,
        label="I accept the Terms of Service.",
        widget=forms.CheckboxInput(attrs={"class": "form-check-input"}),
    )

donate/views.py
from users.models import User
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views.generic import DetailView
from game_logs.models import GameDemo
from order_drawings.models import MyBabyDrawings
from order_codes.models import MyBabyCodes
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.fields.files import ImageField
from .forms import ConfirmForm
from django.views.generic.edit import FormMixin
import datetime
import pytz
from users.forms import UserUpdateForm, ProfileUpdateForm
from babycode import settings
import stripe
from django.core.mail import send_mail
from users.models import Guest

stripe.api_key = settings.STRIPE_SECRET_KEY

# Create your views here.


def index(request):
    # generic donate page at homepage navbar
    return render(request, "donate/index.html")


def charge(request):
    # charge set out by stripe API

    if request.method == "POST":


        amount = int(request.POST["amount"])

        customer = stripe.Customer.create(
            email=request.POST["email"],
            name=request.POST["nickname"],
            source=request.POST["stripeToken"],
        )

        charge = stripe.Charge.create(
            customer=customer,
            amount=amount * 100,
            currency="cad",
            description="Donation",
        )

    return redirect(reverse("donate:success", args=[amount]))


def successMsg(request, args):
    # donated amount
    amount = args
    # set timezone for datetime.min
    utc = pytz.UTC
    # logics for successpage to take user back to previous/latest order: machine or human
    try:
        draw_order = MyBabyDrawings.objects.filter(user_id=request.user.id).latest(
            "date_added"
        )
        draw_order_time = draw_order.date_added
    except MyBabyDrawings.DoesNotExist:
        draw_order = None
        draw_order_time = utc.localize(datetime.datetime.min)
    try:
        machine_order = MyBabyCodes.objects.filter(user_id=request.user.id).latest(
            "date_added"
        )
        machine_order_time = machine_order.date_added
    except MyBabyCodes.DoesNotExist:
        machine_order = None
        machine_order_time = utc.localize(datetime.datetime.min)

    # logics for successpage to take user back to previous/latest order: machine or human
    if machine_order == None and draw_order == None:
        context = {
            "amount": amount
        }
    elif draw_order_time > machine_order_time:
        context = {
            "amount": amount,
            "draw_game_id": draw_order.game_id.id,
        }
    else:
        context = {
            "amount": amount,
            "machine_game_id": machine_order.game_id.id,
        }

    return render(request, "donate/success.html", context)


# Donate page wher user can download their game zipfile.
class MachineCodeDonateView(DetailView):
    model = GameDemo
    template_name = "donate/machinecode.html"

    def get_context_data(self, **kwargs):

        guest = Guest.objects.get(device=self.request.COOKIES['device'])
        ctx = super(MachineCodeDonateView, self).get_context_data(**kwargs)
        try:

            # Preveiw images
            order = MyBabyCodes.objects.filter(
                game_id=self.kwargs["pk"], user_id=guest.pk
            ).latest("date_added")

            imgList = [
                x
                for x in order._meta.fields
                if type(x) == ImageField and getattr(order, x.name)
            ]
            ctx["mybabycodes"] = [getattr(order, x.name) for x in imgList]
            ctx["gamefile"] = getattr(order, "gamefile")
            ctx["game_id"] = getattr(order, "game_id")

        except:

            # TODO: user has no order. Pass for now
            pass

        return ctx


# Get confirmation of drawing ordr and terms of service at HumanCode donate page.
class HumanCodeDonateView(LoginRequiredMixin, FormMixin, DetailView):
    model = GameDemo
    template_name = "donate/humancode.html"
    form_class = ConfirmForm

    def get_success_url(self):
        return reverse("profile")

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form = ConfirmForm(request.POST)

        if form.is_valid():
            # check how many pending orders(confirmed by user, but status not ready).And set a max of three pending orders for now.
            # order not saved confirmed if exceeded three and return to profile page with error message
            pending_order_count = MyBabyDrawings.objects.filter(
                user_id=self.request.user, status=False, confirm_status=True
            ).count()
            if pending_order_count >= 2:
                user_orders = MyBabyDrawings.objects.filter(
                    user_id=request.user.id, confirm_status=True
                ).order_by("-date_added")
                u_form = UserUpdateForm(instance=request.user)
                p_form = ProfileUpdateForm(instance=request.user.profile)
                context = {
                    "error": "Sorry. You have exceeded maximum Drawing Orders of Two.",
                    "user_orders": user_orders,
                    "u_form": u_form,
                    "p_form": p_form,
                }
                return render(request, "users/profile.html", context)

            order = MyBabyDrawings.objects.filter(
                game_id=self.kwargs["pk"], user_id=self.request.user
            ).latest("date_added")

            order.confirm_status = True
            order.save()

            # Send a confirmation email to user

            email_subject = f"New BabyCode Order: #{order.order_id}"
            user = User.objects.get(pk = request.user.id)
            email_user = [user.email]
            email_message = f"""
            Dear {request.user},
            
            Thank you for ordering BabyCode Draw. Estimated completion time is 2 weeks. 
            You will be notified via Email once your order is ready.
            If you have any questions, feel free to contact us with your order id {order.order_id}.
            Thank you,
            babycodes.canada@gmail.com
            (604)760-6289
            The BabyCode Team.
    
            """
            send_mail(
                email_subject,
                email_message,
                settings.EMAIL_HOST_USER,
                email_user,
            )





            return redirect("profile")
        else:

            return self.form_invalid(form)

    def get_context_data(self, **kwargs):
        ctx = super(HumanCodeDonateView, self).get_context_data(**kwargs)
        try:
            # Preveiw images

            order = MyBabyDrawings.objects.filter(
                game_id=self.kwargs["pk"], user_id=self.request.user
            ).latest("date_added")
            imgList = [
                x
                for x in order._meta.fields
                if type(x) == ImageField and getattr(order, x.name)
            ]
            ctx["mybabydrawings"] = [getattr(order, x.name) for x in imgList]

        except:
            # TODO: user has no order. Pass for now
            pass

        return ctx

donate/templates/donate/index.html
{% extends "donate/template.html" %}
{% load static %}
{% block content %}

<style type="text/css">
		/**
		 * The CSS shown here will not be introduced in the Quickstart guide, but shows
		 * how you can use CSS to style your Element's container.
		 */
		.StripeElement {
		  box-sizing: border-box;

		  height: 40px;

		  padding: 10px 12px;

		  border: 1px solid transparent;
		  border-radius: 4px;
		  background-color: white;

		  box-shadow: 0 1px 3px 0 #e6ebf1;
		  -webkit-transition: box-shadow 150ms ease;
		  transition: box-shadow 150ms ease;
		}

		.StripeElement--focus {
		  box-shadow: 0 1px 3px 0 #cfd7df;
		}

		.StripeElement--invalid {
		  border-color: #fa755a;
		}

		.StripeElement--webkit-autofill {
		  background-color: #fefde5 !important;
		}
	</style>


	<script src="https://js.stripe.com/v3/"></script>





	<div id="container">
		<div class="column-6">
			<div id="left-wrapper">
				<img id="profile-pic" src="{% static 'game_logs/images/Evelyn.JPG' %}">
				<div id="left-wrapper-header">
					<h3>Buy Us Baby Food?</h3>
					<h5>One Time Donation</h5>
				</div>
				<div style="clear:left"></div>
				<hr>
				<!-- Add form here -->
				<form action="{% url 'donate:charge' %}" method="post" id="payment-form">
					{% csrf_token %}
					<div class="form-field-12">
						<label for="amount">Choose Amount:</label>
						<br>
						<br>
						<select required name="amount" id="amount">
						  <option selected value="5">$5 --- Here's some baby food, on me :)</option>
						  <option value="10">$10 --- You helped me, so I am going to help you</option>
						  <option value="25">$25 --- I love your Blog!</option>
						</select>
					</div>

					<div class="form-field-6">
						<input required type="text" name="email" placeholder="email...">
					</div>

					<div class="form-field-6">
						<input required type="text" name="nickname" placeholder="Nickname...">
					</div>

				  <div class="form-row">
				    <label for="card-element">
				      Credit or debit card
				    </label>
				    <div id="card-element">
				      <!-- A Stripe Element will be inserted here. -->
				    </div>

				    <!-- Used to display form errors. -->
				    <div id="card-errors" role="alert"></div>
				  </div>

				  <div style="clear:left"></div>
				  <hr>

				 	<input  class="myButton" style="background-color:#e05e5e" type="submit" value="Submit Payment" name="">

				</form>


			</div>
		</div>

		<div class="column-6">
			<div id="right-wrapper">

<!--				<img class="coffee-cup" src="{% static 'images/babyformula.png' %}">-->
				<img class="coffee-cup2" src="{% static 'game_logs/images/babyformula.png' %}">
<!--				<img class="coffee-cup3" src="{% static 'images/babyformula.png' %}">-->
				<h3>If I've provided you with value please consider supporting our efforts ;)</h3>

				<p>Games and source code are free to download, use as you wish :) At no point should you feel obligated to donate. But if you have the means, Thank you!</p>
				<hr>
				<a href="{% url 'game_logs:homepage' %}" class="myButton">Back to Games</a>
			</div>

		</div>
	</div>






	<script>
		// Create a Stripe client.
		var stripe = Stripe('pk_live_51JfXWWDgXSumNuL0RSDYecoBN8o2dex1QWSTrxWhlOxnDKjfUffzYl3jkCx765HSDizVdsyiP1KJcoOZwMT2QK9c00ECENGUyb');

		// Create an instance of Elements.
		var elements = stripe.elements();

		// Custom styling can be passed to options when creating an Element.
		// (Note that this demo uses a wider set of styles than the guide below.)
		var style = {
		  base: {
		    color: '#32325d',
		    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
		    fontSmoothing: 'antialiased',
		    fontSize: '16px',
		    '::placeholder': {
		      color: '#aab7c4'
		    }
		  },
		  invalid: {
		    color: '#fa755a',
		    iconColor: '#fa755a'
		  }
		};

		// Create an instance of the card Element.
		var card = elements.create('card', {style: style});

		// Add an instance of the card Element into the `card-element` <div>.
		card.mount('#card-element');

		// Handle real-time validation errors from the card Element.
		card.addEventListener('change', function(event) {
		  var displayError = document.getElementById('card-errors');
		  if (event.error) {
		    displayError.textContent = event.error.message;
		  } else {
		    displayError.textContent = '';
		  }
		});

		// Handle form submission.
		var form = document.getElementById('payment-form');
		form.addEventListener('submit', function(event) {
		  event.preventDefault();

		  stripe.createToken(card).then(function(result) {
		    if (result.error) {
		      // Inform the user if there was an error.
		      var errorElement = document.getElementById('card-errors');
		      errorElement.textContent = result.error.message;
		    } else {
		      // Send the token to your server.
		      stripeTokenHandler(result.token);
		    }
		  });
		});

		// Submit the form with the token ID.
		function stripeTokenHandler(token) {
		  // Insert the token ID into the form so it gets submitted to the server
		  var form = document.getElementById('payment-form');
		  var hiddenInput = document.createElement('input');
		  hiddenInput.setAttribute('type', 'hidden');
		  hiddenInput.setAttribute('name', 'stripeToken');
		  hiddenInput.setAttribute('value', token.id);
		  form.appendChild(hiddenInput);

		  // Submit the form
		  form.submit();
		}
	</script>




{% endblock content %}

donate/templates/donate/machinecode.html
{% extends "donate/template.html" %}
{% load static %}
{% block content %}

<style type="text/css">
		/**
		 * The CSS shown here will not be introduced in the Quickstart guide, but shows
		 * how you can use CSS to style your Element's container.
		 */
		.StripeElement {
		  box-sizing: border-box;

		  height: 40px;

		  padding: 10px 12px;

		  border: 1px solid transparent;
		  border-radius: 4px;
		  background-color: white;

		  box-shadow: 0 1px 3px 0 #e6ebf1;
		  -webkit-transition: box-shadow 150ms ease;
		  transition: box-shadow 150ms ease;
		}

		.StripeElement--focus {
		  box-shadow: 0 1px 3px 0 #cfd7df;
		}

		.StripeElement--invalid {
		  border-color: #fa755a;
		}

		.StripeElement--webkit-autofill {
		  background-color: #fefde5 !important;
		}

	</style>


	<script src="https://js.stripe.com/v3/"></script>





	<div id="container">
		<div class="column-6">
			<div id="left-wrapper">
				<img id="profile-pic" src="{% static 'game_logs/images/Evelyn.JPG' %}">
				<div id="left-wrapper-header">
					<h3>Buy Us Baby Formula?</h3>
					<h5>One Time Donation</h5>
				</div>
				<div style="clear:left"></div>
				<hr>
				<!-- Add form here -->
				<form action="{% url 'donate:charge' %}" method="post" id="payment-form">
					{% csrf_token %}
					<div class="form-field-12">
						<label for="amount">Choose Amount:</label>
						<br>
						<br>
						<select required name="amount" id="amount">
						  <option selected value="5">$5 --- Here's some baby food, on me :)</option>
						  <option value="10">$10 --- You helped me, so I am going to help you</option>
						  <option value="25">$25 --- I love your channel!</option>
						</select>
					</div>

					<div class="form-field-6">
						<input required type="text" name="email" placeholder="email...">
					</div>

					<div class="form-field-6">
						<input required type="text" name="nickname" placeholder="Nickname...">
					</div>

				  <div class="form-row">
				    <label for="card-element">
				      Credit or debit card
				    </label>
				    <div id="card-element">
				      <!-- A Stripe Element will be inserted here. -->
				    </div>

				    <!-- Used to display form errors. -->
				    <div id="card-errors" role="alert"></div>
				  </div>

				  <div style="clear:left"></div>
				  <hr>

				 	<input  class="myButton" style="background-color:#e05e5e" type="submit" value="Submit Payment" name="">

				</form>


			</div>
		</div>

		<div class="column-6 ">
			<div id="right-wrapper">
			<div class="row">
				<div class="col-sm-4">
<!--					<img class="img-responsive coffee-cup" src="{% static 'images/babyformula.png' %}">-->
				</div>
				<div class="col-sm-4">
					<img class="img-responsive babyformula" src="{% static 'game_logs/images/babyformula.png' %}">
				</div>
				<div class="col-sm-4">
<!--					<img class="img-responsive coffee-cup3" src="{% static 'images/babyformula.png' %}">-->
				</div>
			</div>
			<div class="row">
					<h3>Please consider supporting our efforts.</h3>

					<p>Games and source codes are free to download, use as you wish :) At no point should you feel obligated to donate.But if you have the means, Thank you!</p>
					<hr>
					<a href="{% url 'game_logs:homepage' %}" class="myButton">Back to Games</a>
			</div>

			<div class="row">
				<div class="img-container" style="display: flex; margin-top: 50px">
				{% for image in mybabycodes %}
				<img class="col-sm-3 img-responsive" src="{{ image.url }}">

				{% endfor %}
				</div>
			</div>

				<div class="row">
					<h3>Machine Coded Anime</h3>

					<p>Our AI powered algorithm has cartoonized your photos as show above. They are incorporated into the game for download below. If you don't like the machine code results, try to have your <a href="{% url 'game_logs:game-detail' game_id.id %}#myCarousel">Babycode done by Human </a> for free! </p>

					<hr>

					<button class="myButton" onclick="location.href='{{ gamefile.url }}'">Download Game</button>
				</div>

			</div>
		</div>
	</div>






	<script>
		// Create a Stripe client.
		var stripe = Stripe('pk_live_51JfXWWDgXSumNuL0RSDYecoBN8o2dex1QWSTrxWhlOxnDKjfUffzYl3jkCx765HSDizVdsyiP1KJcoOZwMT2QK9c00ECENGUyb');

		// Create an instance of Elements.
		var elements = stripe.elements();

		// Custom styling can be passed to options when creating an Element.
		// (Note that this demo uses a wider set of styles than the guide below.)
		var style = {
		  base: {
		    color: '#32325d',
		    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
		    fontSmoothing: 'antialiased',
		    fontSize: '16px',
		    '::placeholder': {
		      color: '#aab7c4'
		    }
		  },
		  invalid: {
		    color: '#fa755a',
		    iconColor: '#fa755a'
		  }
		};

		// Create an instance of the card Element.
		var card = elements.create('card', {style: style});

		// Add an instance of the card Element into the `card-element` <div>.
		card.mount('#card-element');

		// Handle real-time validation errors from the card Element.
		card.addEventListener('change', function(event) {
		  var displayError = document.getElementById('card-errors');
		  if (event.error) {
		    displayError.textContent = event.error.message;
		  } else {
		    displayError.textContent = '';
		  }
		});

		// Handle form submission.
		var form = document.getElementById('payment-form');
		form.addEventListener('submit', function(event) {
		  event.preventDefault();

		  stripe.createToken(card).then(function(result) {
		    if (result.error) {
		      // Inform the user if there was an error.
		      var errorElement = document.getElementById('card-errors');
		      errorElement.textContent = result.error.message;
		    } else {
		      // Send the token to your server.
		      stripeTokenHandler(result.token);
		    }
		  });
		});

		// Submit the form with the token ID.
		function stripeTokenHandler(token) {
		  // Insert the token ID into the form so it gets submitted to the server
		  var form = document.getElementById('payment-form');
		  var hiddenInput = document.createElement('input');
		  hiddenInput.setAttribute('type', 'hidden');
		  hiddenInput.setAttribute('name', 'stripeToken');
		  hiddenInput.setAttribute('value', token.id);
		  form.appendChild(hiddenInput);

		  // Submit the form
		  form.submit();
		}
	</script>




{% endblock content %}

donate/templates/donate/success.html
{% extends "donate/template.html" %}
{% load static %}
{% block content %}


<div id="box">
		<img id="succes-icon" src="{% static 'images/check.png' %}">
		<h4>Thank you for your contribution of ${{amount}}!</h4>
		<p>Your support helps funding a trip for Evelyn and Michael to visit their grandma back home.  You should receive a receipt to the email you provided shortly :)</p>
		<hr>
	{% if draw_game_id %}
		<a class="myButton" href="{% url 'donate:humancode' draw_game_id %}">&#x2190;Back to My Order</a>
	{% endif %}
	{% if machine_game_id %}
		<a class="myButton" href="{% url 'donate:machinecode' machine_game_id %}">&#x2190;Back to My Order</a>
	{% endif %}
		<hr>
		<a class="myButton" href="{% url 'game_logs:homepage' %}">&#x2190;Back to Games</a>
	</div>
{% endblock content %}

donate/templates/donate/template.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>Buy Me Baby Food</title>

	<link href="https://fonts.googleapis.com/css?family=Fjalla+One|Inter&display=swap" rel="stylesheet">

	    <!-- favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon.ico' %}">
    <link rel="manifest" href="/site.webmanifest">

	    <!-- Boostrap CSS -->
       <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

<!--    <script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.1.0/bootstrap.min.js"></script>-->

	<!-- Landing page styling -->
	<style type="text/css">

        input[type='checkbox'] {

            width:30px;
            height:30px;
            background:white;
            border-radius:5px;
            border:2px solid #555;
        }
        input[type='checkbox']:checked {
            background: #abd;
        }


		.img-responsive {
			align-content: center;
			display: flex;
			height: auto;
			max-width: 100%;
			max-height: 50px;
			max-width: 250px;
			line-height: 20px; /* whatever the fixed height of the bar is */
		}

		body{
			background-color: #F8F8F8;
		}

		h3, h5{
			font-family: 'Fjalla One', sans-serif;
			font-weight: 100;
		}

		h3{
			font-size: 30px;
		}

		h5{
			font-size: 24px;
		}

		p, label{
			font-family: 'Inter', sans-serif;
		}

		hr{
			color:#fff;
			background-color: #fff;
			border-top:1px solid #fff;
			margin-top:20px;
			margin-bottom: 20px;
		}

		#container{
			width:1200px;
			margin:0 auto;
			padding-top: 3%;
		}

		.column-6{
			width: 50%;
			float:left;
		}

		#left-wrapper{
			background-color: #FFCCCC;
			box-shadow: 0 1px 3px 0 #dce0e6;
		    border-radius: 4px;
		    border: 1px solid transparent;
		    padding: 30px;	
		}

		#right-wrapper{
			padding: 30px;
		}

		#profile-pic{
			width:200px;
			display:block;
			margin: 0 auto;
			border-radius: 50%;
			float:left;

		}

		#left-wrapper-header{
			min-width:50%;
			float:left;
			padding-left:20px;

		}

		#left-wrapper-header h3{
			color:#fff;

		}

		#right-wrapper h3{
			color: #e05e5e;
		}

		.coffee-cup{
			margin-left: 50px;
            min-height: 50px;
			width: 100px;
		}

		.coffee-cup2{
			margin-left: 20px;
            min-height: 75px;
			width: 150px;
		}

		.coffee-cup3{
			margin-left: 20px;
            min-height: 100px;
			width: 200px;
		}

        .babyformula{
			margin-left: 20px;
            min-height: 100px;
			width: 150px;
		}

		/* ------------------------ FORM FIELDS ------------------------ */

		.form-field-12{
			width: 100%;
			margin-bottom: 10px;
			padding-top: 5px;
		}

		.form-field-6{
			width: 50%;
			float:left;
			margin-bottom: 10px;
		}

		select{
			width: 100%;
			height: 60px!important;
			box-shadow: 0 1px 3px 0 #dce0e6;
		    padding: 10px 12px;
		    border-radius: 4px;
		    background-color: #fff;
		    border: 1px solid transparent;
		    font-size: 20px;
		    color:	#44464a;
		}

		input{
		    box-shadow: 0 1px 3px 0 #dce0e6;
		    height:40px;
		    border-radius: 4px;
		    background-color: #fff;
		    border: 1px solid transparent;
		    color:	#44464a;
		    width: 95%;
		    padding: 5px;
		    font-size: 16px;

		}

		input::placeholder {
		  color: #9fa1a6;
		}

		/* ------------------------ BUTTON STYLING ------------------------ */
		.myButton {
			background-color:#e05e5e;
			display:inline-block;
			cursor:pointer;
			color:#ffffff;
			font-family:Verdana;
			font-size:17px;
			padding:10px;
			width:100%;
			border-radius: 0;
			text-decoration:none;
			text-align: center;
			transition: .3s;
		}
		.myButton:hover {
			opacity: .6;
		}

		@media screen and (max-width:1200px){
			#container{
				width:80%;
			}

			.column-6{
				width: 100%;
			}
		}

		@media screen and (max-width:800px){
			#container{
				width:100%;
			}

			.coffee-cup{
				margin-left: 20px;
				width: 50px;
			}

			.coffee-cup2{
				margin-left: 20px;
				width: 75px;
			}

			.coffee-cup3{
				margin-left: 20px;
				width: 100px;
			}

		}
	</style>

	<!-- Success page styling -->
	<style type="text/css">
		h4{
			font-family: 'Fjalla One', sans-serif;
			font-weight: 100;
			font-size: 24px;
		}

		#box{
			max-width: 500px;
			margin:0 auto;
			margin-top: 100px;
			padding:30px;
			background-color: #fff;
			text-align: center;
			box-shadow: 0 1px 3px 0 #dce0e6;
		    border-radius: 4px;
		    border: 1px solid transparent;
		}

		.myButton {
			background-color:#e05e5e;
			display:inline-block;
			cursor:pointer;
			color:#ffffff;
			font-family:Verdana;
			font-size:17px;
			padding:10px;
			width:100%;
			border-radius: 0;
			text-decoration:none;
			text-align: center;
			transition: .3s;
		}
		.myButton:hover {
			opacity: .6;
		}

		#succes-icon{
			width: 100px;

		}
	</style>








</head>
<body>
	{% block content %}

	{% endblock content %}
</body>
</html>