babycode/urls.py
from django.contrib.auth import views as auth_views

from django.urls import path, include

from users import views as user_views


from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib import admin
from game_logs import views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("game_logs.urls")),
    path("register/", user_views.register, name="register"),
    path(
        "login/",
        auth_views.LoginView.as_view(template_name="users/login.html"),
        name="login",
    ),
    path(
        "logout/",
        auth_views.LogoutView.as_view(template_name="users/logout.html"),
        name="logout",
    ),
    path("profile/", user_views.profile, name="profile"),
    path(
        "password-reset/",
        auth_views.PasswordResetView.as_view(template_name="users/password_reset.html"),
        name="password_reset",
    ),
    path(
        "password-reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="users/password_reset_done.html"
        ),
        name="password_reset_done",
    ),
    path(
        "password-reset-confirm/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            template_name="users/password_reset_confirm.html"
        ),
        name="password_reset_confirm",
    ),
    path(
        "password-reset-complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="users/password_reset_complete.html"
        ),
        name="password_reset_complete",
    ),
    path("confirm/", views.confirm, name="confirm"),
    path("validate/", views.validate_email, name="validate_email"),
    path("donate/", include("donate.urls"), name="donate"),
    path("order/", include("order_drawings.urls")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

donate/urls.py
from django.urls import path
from . import views


app_name = "donate"

urlpatterns = [
    path("", views.index, name="index"),
    path("charge/", views.charge, name="charge"),
    path("success/<str:args>/", views.successMsg, name="success"),
    path(
        "machinecode/<int:pk>/",
        views.MachineCodeDonateView.as_view(),
        name="machinecode",
    ),
    path("humancode/<int:pk>/", views.HumanCodeDonateView.as_view(), name="humancode"),
]

game_logs/urls.py
"""Defines URL patterns for game_logs"""

from django.urls import path
from . import views
from .views import GameDemoListView, GameDetailCreateView


app_name = "game_logs"

urlpatterns = [
    # Home page
    path("", GameDemoListView.as_view(), name="homepage"),
    path("about/", views.about, name="about"),
    path("game-detail/<int:pk>/", GameDetailCreateView.as_view(), name="game-detail"),
]

order_drawings/urls.py
from django.urls import path
from .views import OrderDrawingsCreateView

app_name = "order_drawings"

urlpatterns = [
    path("<int:pk>/", OrderDrawingsCreateView.as_view(), name="orderPage"),
]

game_logs/models.py
from django.db import models


# Create your models here.
class GameDemo(models.Model):
    def game_directory_path(self, filename):
        return f"game_logs/game_{self.pk}/{filename}"  # TODO: cant assign pk presave therefore created game_6 folder.

    """Main Game Demostration Videos accessible by Admin """
    title = models.CharField(max_length=100)
    description = models.TextField()
    link_to_video = models.URLField()
    display_image = models.ImageField(
        default="default_game_pic.png", upload_to=game_directory_path
    )
    date_added = models.DateTimeField(auto_now_add=True)
    gamefile = models.FileField(blank=True, upload_to=game_directory_path)
    originalgamefile = models.FileField(blank=True, upload_to=game_directory_path)

    example_image1 = models.ImageField(
        null=True, blank=True, upload_to=game_directory_path
    )  # use GIF
    example_image2 = models.ImageField(
        null=True, blank=True, upload_to=game_directory_path
    )
    example_image3 = models.ImageField(
        null=True, blank=True, upload_to=game_directory_path
    )
    example_image4 = models.ImageField(
        null=True, blank=True, upload_to=game_directory_path
    )

    number_of_characters = models.PositiveSmallIntegerField(default=0)

    class Meta:
        ordering = ["date_added"]

    def __str__(self):
        """Return a string representation of the model"""
        return self.title


class GameCharacter(models.Model):
    def directory_path(self, filename):
        return f"game_logs/characters/{filename}"

    name = models.CharField(max_length=100)
    image = models.ImageField(null=True, blank=True, upload_to=directory_path)
    description = models.TextField()
    game = models.ForeignKey(GameDemo, on_delete=models.CASCADE)
    width = models.PositiveSmallIntegerField()
    height = models.PositiveSmallIntegerField()
    orderimage_index = models.PositiveSmallIntegerField()

    class Meta:
        ordering = ["pk"]

    def __str__(self):
        return self.name


class CharacterPosture(models.Model):
    def directory_path(self, filename):
        return f"game_logs/postures/{filename}"

    name = models.CharField(max_length=50)
    image = models.ImageField(null=True, blank=True, upload_to=directory_path)
    character = models.ForeignKey(GameCharacter, on_delete=models.CASCADE)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.character}{self.name}"

game_logs/forms.py
from django import forms
from django.forms import modelformset_factory
from game_logs.models import GameDemo
from order_codes.models import MyBabyCodes


class OrderForm(forms.ModelForm):
    fields = [
        "image1",
        "image2",
        "image3",
        "image4",
        "image5",
        "image6",
        "image7",
        "image8",
        "image9",
        "image10",
    ]

    class Meta:
        model = MyBabyCodes
        fields = "__all__"


class SubscriberForm(forms.Form):
    email = forms.EmailField(
        label="",
        max_length=50,
        widget=forms.EmailInput(
            attrs={
                "class": "textinput textInput form-control",
                "id": "userEmail",
                "placeholder": "Email",
            }
        ),
    )

    name = forms.CharField(
        label="",
        max_length=50,
        widget=forms.TextInput(
            attrs={
                "class": "textinput textInput form-control",
                "placeholder": "Name",
                "size": "50",
            }
        ),
    )

game_logs/views.py
from django.shortcuts import reverse
from django.views.generic import ListView, CreateView
from .models import GameDemo, GameCharacter
from order_drawings.models import MyBabyDrawings
from django.contrib.auth.mixins import LoginRequiredMixin
from order_codes.models import MyBabyCodes
from contact.models import Contact
from .forms import OrderForm
from babycode import settings
from django.http import JsonResponse
from django.shortcuts import render
from django.conf import settings
from newsletters.models import NewsletterUser
from .forms import SubscriberForm
import random
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from contact.forms import ContactForm
from django.core.mail import send_mail
from users.models import Guest
from django.contrib.auth.models import User
from django.contrib.auth.models import AnonymousUser


# Helper Functions
def random_digits():
    return "%0.12d" % random.randint(0, 999999999999)


# Email confirmation
def confirm(request):
    sub = NewsletterUser.objects.get(email=request.GET["email"])
    if sub.conf_num == request.GET["conf_num"]:
        sub.confirmed = True
        sub.save()
        return render(
            request,
            "game_logs/about.html",
            {
                "confirmed": sub.email,
                "action": "confirmed",
                "contact_form": ContactForm(),
            },
        )
    else:
        return render(
            request,
            "game_logs/about.html",
            {"confirmed": sub.email, "action": "denied", "contact_form": ContactForm()},
        )


def validate_email(request):
    email = request.POST.get("email", None)
    if NewsletterUser.objects.filter(email=email).count() > 0:
        res = JsonResponse({"msg": "Sorry, this email has been used."})
    else:
        res = JsonResponse({"msg": ""})
    return res


# Create your views here.
def index(request):
    """The home page for game logs"""
    game_demos = GameDemo.objects.order_by("date_added")
    context = {"game_demos": game_demos}
    return render(request, "game_logs/index.html", context)


def about(request):

    """The about page to explain the site"""

    # Email subscribe POST (for newsletter) and Contact POST (for contact with questions) all pass into this ABOUT page
    if request.method == "POST":
        # try if request.Post['email'] or request.POST['contact_email'] exist then act accordingly
        try:

            sub = NewsletterUser(
                email=request.POST["email"],
                name=request.POST["name"],
                conf_num=random_digits(),
            )

            try:
                sub.save()
            except:
                return render(
                    request,
                    "game_logs/about.html",
                    {"form": SubscriberForm(),
                     "contact_form": ContactForm(),
                     'error': "Sorry, this E-mail has been used.",
                    }
                )
            # Email confirmtion link to subscriber
            # DISABLE EMAIL CONFIRMATION FOR NEWSLETTER FOR NOW
            # message = Mail(
            #     from_email=settings.EMAIL_HOST_USER,
            #     to_emails=sub.email,
            #     subject="Newsletter Confirmation",
            #     html_content='Thank you {} for signing up for my BabyCode newsletter! \
            #            Please complete the process by \
            #            <a href="{}/?email={}&conf_num={}"> clicking here to \
            #            confirm your registration</a>.'.format(
            #         sub.name,
            #         request.build_absolute_uri("/confirm"),
            #         sub.email,
            #         sub.conf_num,
            #     ),
            # )
            #
            # sg = SendGridAPIClient(settings.SENDGRID_API_KEY)
            #
            #
            # response = sg.send(message)
            return render(
                request,
                "game_logs/about.html",
                {
                    "email": sub.email,
                    "action": "added",
                    "form": SubscriberForm(),
                    "contact_form": ContactForm(),
                },
            )

        except:
            # email Contact information and messages to Admin Email: frugal_jerk@outlook.com
            contact = Contact(
                contact_email=request.POST["contact_email"],
                contact_subject=request.POST["contact_subject"],
                contact_message=request.POST["contact_message"],
            )
            contact.save()

            email_subject = f"New BabyCode Contact: {request.POST['contact_subject']}. Email: {request.POST['contact_email']}"
            email_message = request.POST["contact_message"]
            send_mail(
                email_subject,
                email_message,
                settings.EMAIL_HOST_USER,
                settings.ADMIN_EMAILS,
            )

            return render(
                request,
                "game_logs/about.html/",
                {
                    "contact_subject": contact.contact_subject,
                    "form": SubscriberForm(),
                    "contact_form": ContactForm(),
                },
            )

    else:
        return render(
            request,
            "game_logs/about.html",
            {"form": SubscriberForm(), "contact_form": ContactForm()},
        )

    # return render(request, 'game_logs/about.html')


class GameDemoListView(ListView):
    model = GameDemo
    template_name = "game_logs/index.html"  # <app>/<model>_<viewtype>.html
    context_object_name = "game_demos"
    ordering = ["-date_added"]

#LoginRequiredMixin
# POST REQUEST process order from machine code and save to MyBabyCode model in order_codes app.
class GameDetailCreateView(CreateView):

    template_name = "game_logs/detail.html"
    model = MyBabyCodes
    fields = OrderForm.fields

    def get_success_url(self):
        pk = self.kwargs["pk"]
        return reverse("donate:machinecode", kwargs={'pk': pk})


    def form_valid(self, form):
        form.instance.game_id = GameDemo.objects.get(pk=self.kwargs["pk"])

        # use device cookie to create BabyOrders
        device = self.request.COOKIES['device']
        guest, created = Guest.objects.get_or_create(device=device)
        form.instance.user_id = guest

        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        ctx = super(GameDetailCreateView, self).get_context_data(**kwargs)
        ctx["gamedemo"] = GameDemo.objects.get(pk=self.kwargs["pk"])
        ctx["gamecharacter"] = GameCharacter.objects.filter(game=self.kwargs["pk"])

        # Add logics so only required form fields appear as per number of characters in Gamedemo
        for i in range(len(ctx["form"].fields) - ctx["gamedemo"].number_of_characters):
            ctx["form"].fields.popitem()
        # Making the required from fields required = True for validation purpose
        for _ in ctx["form"].fields.values():
            _.required = True
        return ctx

game_logs/templates/game_logs/basenew.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <title>BabyCode </title>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'game_logs/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'game_logs/favicon.ico' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'game_logs/favicon.ico' %}">
    <link rel="manifest" href="static/game_logs/site.webmanifest" crossorigin="use-credentials">





<!--    &lt;!&ndash; jquery &ndash;&gt;-->
<!--    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>-->

    <!-- Boostrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
<!--    <script src="http://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/2.1.0/bootstrap.min.js"></script>-->


    <!-- Google Font CDN -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato" rel="stylesheet" type="text/css">


    <!-- cropper -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/cropper/4.1.0/cropper.min.css">


    <!-- custom css & js--><!-- update main.js versioning to force browser reload js -->
    <link rel="stylesheet" type="text/css" href="{% static 'game_logs/mainnew.css' %}">

    <script src={% static 'game_logs/main.js' %} defer></script>

</head>
<body id="myPage" data-spy="scroll" data-target=".navbar" data-offset="60">

<!-- Alert Bars -->
        {% if messages %}
            {% for message in messages %}
              <div class="alert alert-success alert-dismissible" id="alert-box" style="margin-bottom: 0; border-radius: 0">
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ message }}
              </div>
            {% endfor %}
          {% endif %}


          {% if email %}
              <div class="alert alert-success alert-dismissible" id="alert-box" style="margin-bottom: 0; border-radius: 0">
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ email }} has been {{ action }}. Thank you for subscribing to our newsletter.
              </div>
          {% endif %}

          {% if confirmed %}
              <div class="alert alert-success alert-dismissible" id="alert-box" style="margin-bottom: 0; border-radius: 0">
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ confirmed }} has been {{ action }}. Thank you.
              </div>
          {% endif %}

            {% if contact_subject %}
              <div class="alert alert-success alert-dismissible" id="alert-box" style="margin-bottom: 0; border-radius: 0">
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                Your contact information and message have been successfully submitted. Thank you {{ contact_subject }}.
              </div>
            {% endif %}


            {% if error %}
              <div class="alert alert-danger alert-dismissible" id="alert-box" style="margin-bottom: 0; border-radius: 0">
                  <button type="button" class="close" data-dismiss="alert">&times;</button>
                {{ error }}
              </div>
            {% endif %}





<!-- Navigation bar -->
<nav class="navbar navbar-default ">
  <div class="container">
    <div class="navbar-header" >
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>

      <a class="navbar-brand" href="{% url 'game_logs:homepage' %}" title="Game Collections"><img class="img-responsive" src="{% static 'game_logs/images/navlogo2.png' %}" alt="Logo" width="300px" height="100px" ></a>

    </div>
    <div class="collapse navbar-collapse" id="myNavbar" aria-expanded="false">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'game_logs:about'  %}" >ABOUT</a></li>

        <li><a href="{% url 'game_logs:about'  %}#services" >SERVICES</a></li>
        <li><a href="{% url 'game_logs:about' %}#portfolio" >PORTFOLIO</a></li>
<!--        <li><a href="{% url 'game_logs:about'  %}#pricing" >PRICING</a></li>-->
        <li><a href="{% url 'game_logs:about'  %}#contact" >CONTACT</a></li>

           {% if user.is_authenticated %}
              <li><a class="nav-item nav-link" href="{% url 'profile' %}">MY PROFILE</a></li>
              <li><a class="nav-item nav-link" href="{% url 'logout' %}"><small>LOGOUT</small></a></li>

            {% else %}
              <li><a class="nav-item nav-link" href="{% url 'login' %}">LOGIN</a></li>
              <li><a class="nav-item nav-link" href="{% url 'register' %}">REGISTER</a></li>
            {% endif %}
        <li><a href="{% url 'donate:index' %}" class="donate"><strong>DONATE</strong></a></li>
      </ul>
    </div>
  </div>
</nav>


<!-- Making scrollspy only active when in 'about' page-->
{% if '/about/' in request.path %}
 <script>
$(document).ready(function(){
  // Add smooth scrolling to all links in navbar + footer link
  $(".navbar a, footer a[href='#myPage']").on('click', function(event) {

   // Make sure this.hash has a value before overriding default behavior
  if (this.hash !== "") {

    // Prevent default anchor click behavior
    event.preventDefault();

    // Store hash
    var hash = this.hash;

    // Using jQuery's animate() method to add smooth page scroll
    // The optional number (900) specifies the number of milliseconds it takes to scroll to the specified area
    $('html, body').animate({
      scrollTop: $(hash).offset().top
    }, 900, function(){

      // Add hash (#) to URL when done scrolling (default click behavior)
      window.location.hash = hash;
      });
    } // End if
  });
})
</script>
{% endif %}


<main role="main">


      {% block content %}{% endblock content %}




</main>



</body>
</html>

game_logs/templates/game_logs/detail.html
{% extends "game_logs/basenew.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}


<!-- Description Section -->
<div class="wrapper-description">
  <div class="col-sm-8 col-centered">
    <div class="description-group text-center">
        <div class="container-fluid">
            <a class="mr-2" href="{{ gamedemo.link_to_video }}" target="_blank" title="Link to Video" >
                <img class="img-fluid" style="margin:auto" src="{{ gamedemo.example_image1.url }}" alt="Game Gif">
            </a>
        </div>
        <div class="container-fluid">
            <h2>{{ gamedemo.title }}</h2>
            <p class="description">{{ gamedemo.description | safe }}</p>
            <hr>

            <p class="description"><button class="btn btn-outline-primary loginbtn" onclick="location.href='{{ gamedemo.originalgamefile.url }}'">Download</button>
            {{ gamedemo.title }} | <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-windows" viewBox="0 0 16 16">
                <path d="M6.555 1.375 0 2.237v5.45h6.555V1.375zM0 13.795l6.555.933V8.313H0v5.482zm7.278-5.4.026 6.378L16 16V8.395H7.278zM16 0 7.33 1.244v6.414H16V0z"></path>
            </svg> Windows 8 or Above.</p>
        </div>
    </div>
    </div>
</div>



<!-- Carousel for image upload -->
<div class="wrapper-form" id="carouselform">
    <div class="col-sm-2"></div>
    <div class="col-sm-10 col-centered">
        <!-- alert box for form validation -->
      <div id="alert-box" class="alert alert-danger not-visible" role="alert"></div>

    <div class="container-fluid makecode" >

        <!-- Pass routing info to javascript for ajax redirect -->
        <link href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css" rel="stylesheet">
        <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
        <div id="js-url" data-url="{% url 'order_drawings:orderPage' gamedemo.id %}"></div>
        <div id="js-url-machine" data-url="{% url 'donate:machinecode' gamedemo.id %}"></div>
        <div id="js-url-human" data-url="{% url 'donate:humancode' gamedemo.id %}"></div>

        {% if user.is_authenticated %}

        <h2>Customize My Game by:   <input id="toggle-event" type="checkbox" checked data-toggle="toggle" data-on="Algorithm" data-off="Artist" data-onstyle="primary" data-offstyle="info">  </h2>
        {% else %}

        <!-- restrict user to machinecode only if not signed in -->
        <div id="js-url-machine" data-url="{% url 'donate:machinecode' gamedemo.id %}"></div>
        <h2>Customize My Game by:
            <span class='test' data-toggle="tooltip" data-placement="top" title="Login Required for Artist Customization">
            <input class="tooltip" id="toggle-event" type="checkbox" checked data-toggle="toggle tooltip" data-on="Algorithm" data-off="" data-onstyle="primary" data-offstyle="info" title="test" disabled>
            </span>
        </h2>

        {% endif %}


            {% csrf_token %}

    <div id="myCarousel" class="carousel slide text-center" data-ride="carousel" data-interval="false" style="min-height: 500px; margin-bottom: 100px; padding-bottom: 200px">
    <!-- Indicators -->


    <!-- Wrapper for slides -->
    <div class="carousel-inner content content col-centered" role="listbox" >

        {% for character in gamecharacter %}


      <div class="item container-fluid text-centered" >

          <h1>{{ character.name}}</h1>
          <p>{{ character.description }}</p>


                <div class="col-sm-6 container-fluid" >
                    <div class="image-upload img-fluid">
                            <label for="id_image{{character.id}}" >
                                <img id="characterimgs" src="{{ character.image.url }}" data-toggle="tooltip" data-placement="top" title="Click me to upload a picture" />
                             </label>
                            <input type="file"  name="image{{ character.orderimage_index }}" accept="image/*" class="clearablefileinput form-control-file" required="" id="id_image{{character.id}}">
                        </div>

                    <p class="not-visible" id="widthimage{{ character.orderimage_index }}">{{ character.width }}</p>
                    <p class="not-visible" id="heightimage{{ character.orderimage_index }}">{{ character.height }}</p>
                </div>

                <div class="col-sm-6 container-fluid " >
                    <!-- making image a click button for upload -->
                    <div class="img-responsive img-fluid" style="min-height: {{ character.height }}px; width: {{ character.width }}" id="image{{ character.orderimage_index }}"></div>

                </div>




      </div>
        {% endfor %}


        <!-- Loading GIF implemented -->
        <div class="item active">
            <h3>Instruction</h3>
            <div class="col-sm-1"></div>
            <div class="col-sm-4">
                <img class="img-container" id="loadingDiv" src="{% static 'game_logs/images/loadcat.gif' %}" style="min-height: 300px">
                <img class="img-container" id="loadedDiv" src="{% static 'game_logs/images/loadcatstatic.png' %}" style="min-height: 300px">

            </div>

            <!-- Shows when loading -->
            <div class="col-sm-6" id="loadingDiv2">
                <br>
                <img class="img-fluid" id="loadingDiv2" src="{% static 'game_logs/images/loading.gif' %}">
            </div>
            <!-- Become hidden when loading -->
            <div class="col-sm-6" id="loadedDiv2" style="text-align: left">
            <br>
                <p>Click each game character to upload an image. Crop the image to match the character's contour.</p>
                <p>Press the upload button and wait for AI/OpenCV Engine to cartoonize your images into the game.</p>
                <p>Download the zipfile and unzip. Double Click "{{ gamedemo.title }}.exe" to play.</p>
                <button class="btn btn-outline-primary loginbtn" id="confirm-btn" type="submit">Upload My Baby Images</button>
            </div>

            <div class="col-sm-1"></div>

        </div>



    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>

  </div>
</div>




        </div>
    </div>
    <div class="col-sm-2"></div>







</div>








<!-- footer area to account for different image height -->
<div class="wrapper-form">

  <div class="col-sm-10 col-centered">

    <div class="container-fluid makecode">



    </div>

  </div>

</div>









<!--&lt;!&ndash; Image Upload Forms &ndash;&gt;-->
<!--<div class="wrapper-form">-->

<!--  <div class="col-sm-8 col-centered">-->

<!--    <div class="container-fluid makecode">-->

<!--      <h2>Make New BabyCode</h2>-->
<!--      <h4><small class="article-metadata" style="text-align: right" ><a href="#" title="Click to learn more">Link for Instruction</a></small></h4>-->
<!--      <br>-->

<!--            {% csrf_token %}-->


<!--        {% for character in gamecharacter %}-->

<!--    <div class="col-sm-6 container-fluid">-->


<!--        <div class="container-fluid img-container">-->
<!--            <h1>{{ character.name}}</h1>-->
<!--            <p>{{ character.description }}</p>-->


<!--            <div class="image-upload img-container">-->
<!--                    <label for="id_image{{character.id}}" >-->

<!--                        <img id="characterimgs" src="{{ character.image.url }}"  />-->
<!--                     </label>-->

<!--                    <input type="file"  name="image{{ character.orderimage_index }}" accept="image/*" class="clearablefileinput form-control-file" required="" id="id_image{{character.id}}">-->
<!--                </div>-->

<!--            <p class="not-visible" id="widthimage{{ character.orderimage_index }}">{{ character.width }}</p>-->
<!--            <p class="not-visible" id="heightimage{{ character.orderimage_index }}">{{ character.height }}</p>-->
<!--        </div>-->
<!--        <div class="img-container">-->
<!--&lt;!&ndash;            <img class="img-characters" src="{{ character.image.url }}" alt="{{ character.name }}">&ndash;&gt;-->
<!--            &lt;!&ndash; making image a click button for upload &ndash;&gt;-->


<!--                <div class='imagebox img-container' id="image{{ character.orderimage_index }}" >-->
<!--                    &lt;!&ndash; crop image box place holder &ndash;&gt;-->
<!--                </div>-->

<!--        </div>-->



<!--    </div>-->


<!--        {% endfor %}-->

<!--    </div>-->

<!--        <button class="btn btn-outline-primary loginbtn" id="confirm-btn" type="submit">confirm</button>-->

<!--    </div>-->
<!--</div>-->


    <!-- carousel-->














<!-- pseudoform after the submit button so the Ajax would send form only once -->
<form action="#" id="image-form">
    <p id="form-length" class="not-visible">{{ gamecharacter|length }}</p>
<!--    <input type="file"  name="image{{character.id}}" accept="image/*" class="clearablefileinput form-control-file" required="" id="id_image{{character.id}}">-->






{% endblock content %}